--1. 전체 사원 중 3번째로 빠르게 입사한 사원의 이름과 입사일을 연-월-일 포멧으로 조회하시오.
-- 입사일이 가장 빠른 사원 + RANK까지 ORDER BY안에 함수로 작성 안해도 되기때문에
SELECT FIRST_NAME 
     , HIRE_DATE
     , ROW_NUMBER() OVER( ORDER BY HIRE_DATE ASC) AS RANK
  FROM EMPLOYEES
;
-- RANK 사용하기 위해서 인라인 뷰 사용
SELECT FIRST_NAME 
	 , TO_CHAR(HIRE_DATE, 'YYYY-MM-DD') 
  FROM (SELECT FIRST_NAME 
		     , HIRE_DATE 
    		 , ROW_NUMBER() OVER( ORDER BY HIRE_DATE ASC) AS RANK
		  FROM EMPLOYEES)
 WHERE RANK = 3
;
--2. 전체 사원 중 11번째로 늦게 입사한 사원의 이름과 입사일을 연-월-일 포멧으로 조회하시오.
-- 전체 사원이름, 입사일 날짜가 늦은 순으로 정렬
SELECT FIRST_NAME 
     , HIRE_DATE
     , ROW_NUMBER() OVER( ORDER BY HIRE_DATE DESC) AS RANK
  FROM EMPLOYEES
;
-- RANK를 사용하기 위해서 인라인 뷰를 사용
SELECT FIRST_NAME 
     , TO_CHAR(HIRE_DATE , 'YYYY-MM-DD')
  FROM (SELECT FIRST_NAME 
		     , HIRE_DATE
		     , ROW_NUMBER() OVER( ORDER BY HIRE_DATE DESC) AS RANK
		  FROM EMPLOYEES)
 WHERE RANK = 11
;
--3. 2006년에 입사한 사원 중 2번째로 빠르게 입사한 사원의 이름과 입사일을 연-월-일 포멧으로 조회하시오.
-- 2006년에 입사한 사원
SELECT FIRST_NAME 
     , HIRE_DATE 
     , ROW_NUMBER() OVER( ORDER BY HIRE_DATE ASC ) AS RANK
  FROM EMPLOYEES
 WHERE TO_CHAR(HIRE_DATE , 'YYYY') = '2006'
;
-- RANK를 사용하기 위해서 인라인 뷰 사용
SELECT FIRST_NAME 
	 , TO_CHAR(HIRE_DATE , 'YYYY-MM-DD')
  FROM (SELECT FIRST_NAME 
		     , HIRE_DATE 
		     , ROW_NUMBER() OVER( ORDER BY HIRE_DATE ASC ) AS RANK
		  FROM EMPLOYEES
		 WHERE TO_CHAR(HIRE_DATE , 'YYYY') = '2006')
 WHERE RANK = 2
;
--4. 3번째로 많은 사원이 수행중인 직무의 이름과 사원 수를 조회하시오.
-- 부서별 사원의 수
SELECT D.DEPARTMENT_NAME 
     , COUNT(E.EMPLOYEE_ID ) AS EMP_CNT
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
 GROUP BY D.DEPARTMENT_NAME
;
-- COUNT별 순으로 사원이 많은 순으로 정렬
SELECT DEPARTMENT_NAME
     , EMP_CNT 
     , DENSE_RANK() OVER( ORDER BY EMP_CNT DESC) AS RANK
  FROM (SELECT D.DEPARTMENT_NAME 
		     , COUNT(E.EMPLOYEE_ID ) AS EMP_CNT
		  FROM EMPLOYEES E
		 INNER JOIN DEPARTMENTS D
		    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
		 GROUP BY D.DEPARTMENT_NAME)
;
-- RANK를 쓰기 위해 인라인뷰 사용
SELECT DEPARTMENT_NAME
     , EMP_CNT 
  FROM (SELECT DEPARTMENT_NAME
		     , EMP_CNT 
		     , DENSE_RANK() OVER( ORDER BY EMP_CNT ASC) AS RANK
		  FROM (SELECT D.DEPARTMENT_NAME 
				     , COUNT(E.EMPLOYEE_ID ) AS EMP_CNT
				  FROM EMPLOYEES E
				 INNER JOIN DEPARTMENTS D
				    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
				 GROUP BY D.DEPARTMENT_NAME))
 WHERE RANK IN 3
;
--4. 3번째로 많은 사원이 수행중인 직무의 이름과 사원 수를 조회하시오.
--직무별 사원의 수
SELECT J.JOB_TITLE 
     , COUNT(E.EMPLOYEE_ID ) AS EMP_CNT
  FROM EMPLOYEES E
 INNER JOIN JOBS J
    ON J.JOB_ID = E.JOB_ID 
 GROUP BY J.JOB_TITLE 
;

-- 사원이 많은 순으로 정렬
SELECT JOB_TITLE 
     , EMP_CNT 
     , DENSE_RANK() OVER( ORDER BY EMP_CNT  DESC) AS RANK
  FROM (SELECT J.JOB_TITLE 
		     , COUNT(E.EMPLOYEE_ID ) AS EMP_CNT
		  FROM EMPLOYEES E
		 INNER JOIN JOBS J
		    ON J.JOB_ID = E.JOB_ID 
		 GROUP BY J.JOB_TITLE )
;
-- RANK 사용
SELECT JOB_TITLE 
     , EMP_CNT 
     , RANK
  FROM (SELECT JOB_TITLE 
		     , EMP_CNT 
		     , DENSE_RANK() OVER( ORDER BY EMP_CNT  DESC) AS RANK
		  FROM (SELECT J.JOB_TITLE 
				     , COUNT(E.EMPLOYEE_ID ) AS EMP_CNT
				  FROM EMPLOYEES E
				 INNER JOIN JOBS J
				    ON J.JOB_ID = E.JOB_ID 
				 GROUP BY J.JOB_TITLE ))
  WHERE RANK = 3
;

--1. 대륙, 국가, 도시, 부서, 직무별 사원의 수, 사원들의 평균 급여를 조회하세요.
SELECT R.REGION_NAME
     , C.COUNTRY_NAME
     , L.CITY
     , D.DEPARTMENT_NAME
     , J.JOB_TITLE
     , COUNT(E.EMPLOYEE_ID )
     , AVG(E.SALARY )
  FROM EMPLOYEES E
 INNER JOIN JOBS J
    ON J.JOB_ID = E.JOB_ID 
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON L.LOCATION_ID = D.LOCATION_ID 
 INNER JOIN COUNTRIES C
    ON C.COUNTRY_ID  = L.COUNTRY_ID 
 INNER JOIN REGIONS R
    ON R.REGION_ID = C.REGION_ID 
 GROUP BY R.REGION_NAME , C.COUNTRY_NAME , L.CITY , D.DEPARTMENT_NAME ,J.JOB_TITLE
;
 
--2. 각 부서장 사원번호별 사원의 수를 조회하고 사원의 수로 오름차순 정렬하세요.
SELECT E.MANAGER_ID 
     , COUNT(E.EMPLOYEE_ID ) E_CNT
  FROM EMPLOYEES E -- 사원
 INNER JOIN EMPLOYEES E_MAN -- 상사
    ON E_MAN.EMPLOYEE_ID = E.MANAGER_ID 
 GROUP BY E.MANAGER_ID 
 ORDER BY E_CNT ASC 
;
 
--3. 직무가 받을 수 있는 평균 급여(MAX_SALARY, MIN_SALARY)보다 많은 급여를 받는 사원들을 직무별 사원의 수로 조회하세요.
SELECT
  FROM EMPLOYEES 
 

SELECT AVG(MAX_SALARY + MIN_SALARY )
  FROM JOBS
 GROUP BY JOB_TITLE 
;

SELECT J.JOB_ID 
	 , COUNT(E.EMPLOYEE_ID )
  FROM EMPLOYEES E
 INNER JOIN JOBS J
    ON J.JOB_ID = E.JOB_ID 
 WHERE E.SALARY > (J.MAX_SALARY + J.MIN_SALARY) / 2
 GROUP BY J.JOB_ID 
-- WHERE E.SALARY >  (SELECT AVG(MAX_SALARY + MIN_SALARY )
-- 					  FROM JOBS
--					 GROUP BY JOB_TITLE )
-- GROUP BY J.JOB_TITLE 
;


--4. 모든 부서장들의 부하직원들을 계층 조회하세요.

-- INNER JOIN

--1. 사원 이름과 부서명을 함께 조회하시오.
SELECT E.FIRST_NAME
     , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
;
--2. 사원 이름과 직무명을 함께 조회하시오.
SELECT E.FIRST_NAME 
     , J.JOB_TITLE 
  FROM EMPLOYEES E
 INNER JOIN JOBS J
    ON J.JOB_ID = E.JOB_ID 
;
--3. 사원 이름, 부서명, 근무 도시를 조회하시오.
SELECT E.FIRST_NAME 
     , D.DEPARTMENT_NAME 
     , L.CITY 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D -- 사원 + 부서
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L -- 부서 + 근무 도시
    ON L.LOCATION_ID = D.LOCATION_ID 
;
--4. 부서명과 국가명을 조회하시오
SELECT D.DEPARTMENT_NAME 
     , C.COUNTRY_NAME 
  FROM DEPARTMENTS D
 INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID 
 INNER JOIN COUNTRIES C
    ON C.COUNTRY_ID  = L.COUNTRY_ID 
;

--5. 직무변경 이력이 있는 사원의 이름과 이전 직무를 조회하시오.
SELECT E.FIRST_NAME 
     , J.JOB_TITLE
  FROM EMPLOYEES E
 INNER JOIN JOB_HISTORY JH
    ON JH.EMPLOYEE_ID = E.EMPLOYEE_ID 
 INNER JOIN JOBS J
    ON JH.JOB_ID = J.JOB_ID 
;
--6. 부서번호와 부서장의 이름을 조회하시오.
SELECT D.DEPARTMENT_ID 
     , E.FIRST_NAME 
  FROM DEPARTMENTS D
 INNER JOIN EMPLOYEES E
    ON D.MANAGER_ID = E.EMPLOYEE_ID
;
--7. 사원 이름, 부서명, 직무명을 한 번에 조회하시오.
SELECT E.FIRST_NAME 
     , D.DEPARTMENT_NAME 
     , J.JOB_TITLE 
  FROM EMPLOYEES E
 INNER JOIN JOBS J
    ON J.JOB_ID  = E.JOB_ID 
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID  = E.DEPARTMENT_ID 
;
--8. 각 사원의 이름과 그 사원의 상사 이름을 함께 조회하시오.
SELECT E1.FIRST_NAME
     , E2.FIRST_NAME 
  FROM EMPLOYEES E1 -- 사원
 INNER JOIN EMPLOYEES E2 -- 상사
    ON E2.MANAGER_ID  = E1.EMPLOYEE_ID 
;
--9. 모든 사원의 이름, 급여, 직무명, 부서명, 도시명, 주소, 우편번호, 국가명, 대륙명을 조회하시오.
SELECT E.FIRST_NAME 
     , E.SALARY 
     , J.JOB_TITLE 
     , D.DEPARTMENT_NAME 
     , L.CITY 
     , L.STREET_ADDRESS 
     , L.POSTAL_CODE 
     , C.COUNTRY_NAME 
     , R.REGION_ID 
  FROM EMPLOYEES E 
 INNER JOIN JOBS J -- 사원 + 직무
    ON J.JOB_ID  = E.JOB_ID 
 INNER JOIN DEPARTMENTS D -- 사원 + 부서
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
 INNER JOIN LOCATIONS L -- 부서 + 도시
    ON L.LOCATION_ID   = D.LOCATION_ID 
 INNER JOIN COUNTRIES C
    ON C.COUNTRY_ID = L.COUNTRY_ID 
 INNER JOIN REGIONS R
    ON R.REGION_ID = C.REGION_ID 
;
--10. 직무변경 이력이 있는 사원의 이름, 이전 직무명, 이전 부서명을 조회하시오.
SELECT E.FIRST_NAME 
     , J.JOB_TITLE 
     , D.DEPARTMENT_NAME 
  FROM JOB_HISTORY JH
 INNER JOIN EMPLOYEES E
    ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
 INNER JOIN JOBS J
    ON J.JOB_ID  = JH.JOB_ID 
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = JH.DEPARTMENT_ID 
;
--11. 직무변경 이력이 있는 사원의 이름, 현재 직무명, 현재 부서명을 조회하시오.
SELECT E.FIRST_NAME 
     , J.JOB_TITLE 
     , D.DEPARTMENT_NAME 
  FROM JOB_HISTORY JH
 INNER JOIN EMPLOYEES E
    ON E.EMPLOYEE_ID  = JH.EMPLOYEE_ID
 INNER JOIN JOBS J
    ON J.JOB_ID = E. JOB_ID 
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
;
--12. 직무변경 이력이 있는 사원의 이름, 이전에 근무했던 부서의 번호, 이전에 근무했던 도시의 이름을 조회하시오.
SELECT E.FIRST_NAME 
     , JH.DEPARTMENT_ID 
     , L.CITY 
  FROM JOB_HISTORY JH
 INNER JOIN EMPLOYEES E
    ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID 
 INNER JOIN DEPARTMENTS D
    ON D.DEPARTMENT_ID = JH.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
    ON L.LOCATION_ID = D.LOCATION_ID 
;
--13. 'Tokyo'시에서 근무중인 사원의 이름을 조회하시오.
-- 도쿄의 지역번호 1200
SELECT LOCATION_ID 
  FROM LOCATIONS
 WHERE CITY = 'Tokyo'
;

-- 지역번호가 1200인 부서번호
SELECT DEPARTMENT_ID 
  FROM DEPARTMENTS
 WHERE LOCATION_ID = (SELECT LOCATION_ID 
 					    FROM LOCATIONS
 					   WHERE CITY = 'Tokyo')
;

-- 부서번호를 가진 사원
SELECT FIRST_NAME 
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID  = (SELECT DEPARTMENT_ID 
						   FROM DEPARTMENTS
						  WHERE LOCATION_ID = (SELECT LOCATION_ID 
						 	 				     FROM LOCATIONS
						 					    WHERE CITY = 'Tokyo'))
;

--14. 'Kuwait'국가에서 근무중인 사원의 직무명을 중복없이 조회하시오.
-- Kuwait 국가의 국가 번호 KW
SELECT COUNTRY_ID 
  FROM COUNTRIES
 WHERE COUNTRY_NAME = 'Kuwait'
;

-- KW국가아이디를 가진 지역 아이디
SELECT LOCATION_ID 
  FROM LOCATIONS
 WHERE COUNTRY_ID = (SELECT COUNTRY_ID 
					   FROM COUNTRIES
					  WHERE COUNTRY_NAME = 'Kuwait')
;

-- 지역 아이디를 가진 부서 번호
SELECT DEPARTMENT_ID 
  FROM DEPARTMENTS
 WHERE LOCATION_ID = (SELECT LOCATION_ID 
					    FROM LOCATIONS
					   WHERE COUNTRY_ID = (SELECT COUNTRY_ID 
										     FROM COUNTRIES
										    WHERE COUNTRY_NAME = 'Kuwait'))
;

-- 부서번호를 가진 사원의 직무아이디
SELECT JOB_ID 
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID 
						  FROM DEPARTMENTS
						 WHERE LOCATION_ID = (SELECT LOCATION_ID 
											    FROM LOCATIONS
											   WHERE COUNTRY_ID = (SELECT COUNTRY_ID 
																     FROM COUNTRIES
																    WHERE COUNTRY_NAME = 'Kuwait')))
;

-- 직무아이디를 가진 직무명
SELECT JOB_TITLE 
  FROM JOBS
 WHERE JOB_ID =(SELECT JOB_ID 
				  FROM EMPLOYEES
				 WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID 
										  FROM DEPARTMENTS
										 WHERE LOCATION_ID = (SELECT LOCATION_ID 
															    FROM LOCATIONS
															   WHERE COUNTRY_ID = (SELECT COUNTRY_ID 
																				     FROM COUNTRIES
																				    WHERE COUNTRY_NAME = 'Kuwait'))))
;

--1. 이름이 'S'로 시작하는 사원을 조회하시오.
SELECT EMPLOYEE_ID
     , FIRST_NAME
     , LAST_NAME
     , EMAIL
     , PHONE_NUMBER
     , HIRE_DATE
     , JOB_ID
     , SALARY
     , COMMISSION_PCT
     , MANAGER_ID
     , DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE 'S%'
;

SELECT FIRST_NAME
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE 'S%'
;
--2. 이름에 'an'이 포함된 사원을조회하시오.
SELECT FIRST_NAME 
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '%an%'
;
--3. EMAIL이 'A'로 끝나는 사원을 조회하시오.
SELECT EMAIL 
  FROM EMPLOYEES
 WHERE EMAIL LIKE '%A'
;
--4. 이름을 모두 대문자로 변환해 조회하시오.
SELECT UPPER(FIRST_NAME )
  FROM EMPLOYEES
;
--5. 성을 모두 소문자로 변환해 조회하시오.
SELECT LOWER(LAST_NAME )
  FROM EMPLOYEES
;
--6. 전체 사원 수를 조회하시오.
SELECT COUNT(EMPLOYEE_ID )
  FROM EMPLOYEES
;
--7. 전체 사원의 급여 합계를 조회하시오.
SELECT SUM(SALARY)
  FROM EMPLOYEES
;
--8. 전체 사원의 평균 급여를 조회하시오.
SELECT AVG(SALARY )
  FROM EMPLOYEES
;

--9. 가장 높은 급여와 가장 낮은 급여를 함께 조회하시오.
SELECT MAX(SALARY )
     , MIN(SALARY )
  FROM EMPLOYEES
;
--10. 부서별 사원 수를 조회하시오.
SELECT COUNT(EMPLOYEE_ID )
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID 
;
--11. 부서별 평균 급여를 조회하시오.
SELECT AVG(SALARY )
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID 
;
--
--12. 직무아이디별 최고 급여와 평균 급여를 조회하시오.
SELECT MAX(SALARY )
     , AVG(SALARY )
  FROM EMPLOYEES
 GROUP BY JOB_ID 
;
--13. 부서아이디별, 직무아이디별 사원 수를 함께 조회하시오.
SELECT JOB_ID 
     , DEPARTMENT_ID 
     , COUNT(EMPLOYEE_ID )
  FROM EMPLOYEES
 GROUP BY JOB_ID 
     , DEPARTMENT_ID 
;
--14. 상사번호별로 관리하는 사원 수를 조회하시오.
SELECT COUNT(EMPLOYEE_ID )
  FROM EMPLOYEES
 GROUP BY MANAGER_ID 
;
--15. 사원 수가 5명 이상인 부서번호만 조회하시오.
SELECT DEPARTMENT_ID 
     , COUNT(EMPLOYEE_ID ) 
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID 
 HAVING COUNT(EMPLOYEE_ID ) >= 5
;
--16. 평균 급여가 8000 이상인 부서아이디만 조회하시오.
SELECT DEPARTMENT_ID 
     , AVG(SALARY )
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID 
HAVING AVG(SALARY ) >= 8000
;
--17. 최고 급여가 15000을 초과하는 직무아이디만 조회하시오.
SELECT JOB_ID
	 , MAX(SALARY )
  FROM EMPLOYEES
 GROUP BY JOB_ID 
HAVING MAX(SALARY ) > 15000
;
--18. 부서별 급여 합계가 30000을 초과하는 부서아이디만 조회하시오.
SELECT DEPARTMENT_ID 
     , SUM(SALARY )
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID
 HAVING SUM(SALARY ) > 30000
;
--19. 관리하는 사원이 2명 이상인 매니저만 조회하시오.
SELECT MANAGER_ID 
     , COUNT(EMPLOYEE_ID )
  FROM EMPLOYEES
 GROUP BY MANAGER_ID 
HAVING COUNT(EMPLOYEE_ID ) >= 2
;
--20. 부서별 급여 합계가 30000을 초과하는 부서아이디만 조회하시오.
--
--21. 관리하는 사원이 2명 이상인 매니저만 조회하시오.
--
--22. 전체 평균 급여보다 높은 급여를 받는 사원을 조회하시오.
-- 1. 평균 급여 6461.831775700934579439252336448598130841
SELECT AVG(SALARY )
  FROM EMPLOYEES
;
-- 2. 평균 급여보다 높은 급여를 받는 사원
SELECT EMPLOYEE_ID 
  FROM EMPLOYEES 
 WHERE SALARY > 6461.831775700934579439252336448598130841
;

-- 3. 
SELECT EMPLOYEE_ID 
  FROM EMPLOYEES 
 WHERE SALARY > (SELECT AVG(SALARY )
                   FROM EMPLOYEES)
;
--23. 'IT' 부서에서 근무하는 사원을 조회하시오.
--1. IT부서의 부서번호 60
SELECT DEPARTMENT_ID 
  FROM DEPARTMENTS 
 WHERE DEPARTMENT_NAME  = 'IT'
;
-- 2. IT 부서번호에서 근무하는 사원
SELECT EMPLOYEE_ID 
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID = 60
;

SELECT EMPLOYEE_ID 
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID 
  						  FROM DEPARTMENTS 
 						 WHERE DEPARTMENT_NAME  = 'IT')
;
--24. 가장 급여가 높은 사원을 조회하시오.
--1. 높은 급여 24000
SELECT MAX(SALARY )
  FROM EMPLOYEES
;
--2. 높은 급여의 사원
SELECT EMPLOYEE_ID 
  FROM EMPLOYEES
 WHERE SALARY  = (SELECT MAX(SALARY )
                    FROM EMPLOYEES)
;
--25. 'King'이라는 성을 가진 사원과 같은 부서에서 근무하는 사원을 조회하시오. (본인 제외)
--1. KING이라는 성을 가진 사원의 부서번호 80 90
SELECT DEPARTMENT_ID  
  FROM EMPLOYEES
 WHERE LAST_NAME = 'King'
;

SELECT EMPLOYEE_ID
     , LAST_NAME 
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID  
  						   FROM EMPLOYEES
                          WHERE LAST_NAME LIKE 'King')
   AND LAST_NAME != 'King'
;
--26. 사원이 한 명도 없는 부서번호와 부서명을 조회하시오.
--1. 사원들이 근무중인 부서번호
SELECT DISTINCT DEPARTMENT_ID 
  FROM EMPLOYEES
;

SELECT DEPARTMENT_ID 
     , DEPARTMENT_NAME 
  FROM DEPARTMENTS
 WHERE DEPARTMENT_ID NOT IN (SELECT DISTINCT DEPARTMENT_ID 
                               FROM EMPLOYEES
                              WHERE DEPARTMENT_ID IS NOT NULL)
;
--
--28. 직무변경 이력이 있는 사원의 이름과 성을 조회하시오.
-- 1. 직무가 변경이력이 있는 사원번호
SELECT EMPLOYEE_ID 
  FROM JOB_HISTORY
;

SELECT FIRST_NAME 
     , LAST_NAME 
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID IN (SELECT EMPLOYEE_ID 
                         FROM JOB_HISTORY)
;
--29. 직무변경 이력이 없는 사원의 이름과 성을 조회하시오.
SELECT FIRST_NAME 
     , LAST_NAME 
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID NOT IN (SELECT EMPLOYEE_ID 
                             FROM JOB_HISTORY)
;
