CREATE TABLE "MV" (
	"MV_ID"	VARCHAR2(50 CHAR)		NOT NULL,
	"TTL"	VARCHAR2(40 CHAR)		NOT NULL,
	"MV_RTNG"	VARCHAR2(3 CHAR)		NULL,
	"RNNG_TM"	NUMBER(5, 0)		NULL,
	"RLS_DT"	DATE		NULL,
	"SMMR"	VARCHAR2(420 CHAR)		NULL,
	"MAIN_PSTR_URL"	CLOB		NULL,
	"FB_URL"	VARCHAR2(4000 CHAR)		NULL,
	"X_URL"	VARCHAR2(4000 CHAR)		NULL,
	"INSTA_URL"	VARCHAR2(4000 CHAR)		NULL,
	"TGLN"	VARCHAR2(55  CHAR)		NULL,
	"ORGN_TTL"	VARCHAR2(45  CHAR)		NULL,
	"PLYNG"	VARCHAR2(5  CHAR)		NOT NULL,
	"ORGN_LNGG"	VARCHAR2(5  CHAR)		NOT NULL,
	"BDGT"	NUMBER(10, 0)		NULL,
	"BX_OFFC_RVN"	NUMBER(10, 0)		NULL
);

COMMENT ON COLUMN "MV"."RNNG_TM" IS '분 단위로 작성';

COMMENT ON COLUMN "MV"."BDGT" IS '달러 단위로 환산해서 작성';

COMMENT ON COLUMN "MV"."BX_OFFC_RVN" IS '달러 단위로 환산해서 작성';

CREATE TABLE "GNR" (
	"GNR_ID"	VARCHAR2(20 CHAR)		NOT NULL,
	"NM"	VARCHAR2(20 CHAR)		NOT NULL
);

CREATE TABLE "MV_GNR" (
	"MV_GNR_ID"	VARCHAR2(20 CHAR)		NOT NULL,
	"MV_ID"	VARCHAR2(50 CHAR)		NOT NULL,
	"GNR_ID2"	VARCHAR2(20 CHAR)		NOT NULL
);

COMMENT ON COLUMN "MV_GNR"."MV_GNR_ID" IS 'MG-연월일(8자리)-일련번호(6자리)';

CREATE TABLE "INVLVD" (
	"INVLVD_ID"	VARCHAR2(40 CHAR)		NOT NULL,
	"INVLVD_PRFL"	CLOB		NULL,
	"NM"	VARCHAR2(20 CHAR)		NOT NULL
);

CREATE TABLE "KWRD" (
	"KWRD_ID"	VARCHAR2(30 CHAR)		NOT NULL,
	"KWRD"	VARCHAR2(30 CHAR)		NOT NULL
);

CREATE TABLE "BCKGRND" (
	"BCKGRND_ID"	VARCHAR2(20 CHAR)		NOT NULL,
	"MV_ID"	VARCHAR2(50 CHAR)		NOT NULL,
	"BCKGRD_URL"	CLOB		NOT NULL
);

COMMENT ON COLUMN "BCKGRND"."BCKGRND_ID" IS 'BG-연월일(8자리)-일련번호(6자리)';

CREATE TABLE "FLMMR" (
	"FLMMKR_ID"	VARCHAR2(20 CHAR)		NOT NULL,
	"MV_ID"	VARCHAR2(50 CHAR)		NOT NULL,
	"INVLVD_ID"	VARCHAR2(40 CHAR)		NOT NULL,
	"FLMMKR"	VARCHAR2(30 CHAR)		NULL,
	"PRT"	VARCHAR2(10 CHAR)		NULL
);

COMMENT ON COLUMN "FLMMR"."FLMMKR_ID" IS 'FL-연월일(8자리)-일련번호(6자리)';

CREATE TABLE "VD" (
	"VD_ID"	VARCHAR2(20 CHAR)		NOT NULL,
	"MV_ID"	VARCHAR2(50 CHAR)		NOT NULL,
	"VD_URL"	CLOB		NOT NULL
);

COMMENT ON COLUMN "VD"."VD_ID" IS 'VD-연월일(8자리)-일련번호(6자리)';

CREATE TABLE "APPR" (
	"APPR_ID"	VARCHAR2(20 CHAR)		NOT NULL,
	"MV_ID"	VARCHAR2(50 CHAR)		NOT NULL,
	"INVLVD_ID"	VARCHAR2(40 CHAR)		NOT NULL,
	"RL"	VARCHAR2(30 CHAR)		NULL
);

COMMENT ON COLUMN "APPR"."APPR_ID" IS 'AP-연월일(8자리)-일련번호(6자리)';

CREATE TABLE "MV_KWRD" (
	"MV_KWRD_ID"	VARCHAR2(20 CHAR)		NOT NULL,
	"MV_ID"	VARCHAR2(50 CHAR)		NOT NULL,
	"KWRD_ID2"	VARCHAR2(30 CHAR)		NOT NULL
);

COMMENT ON COLUMN "MV_KWRD"."MV_KWRD_ID" IS 'MK-연월일(8자리)-일련번호(6자리)';

CREATE TABLE "PSTR" (
	"PSTR_ID"	VARCHAR2(20 CHAR)		NOT NULL,
	"MV_ID"	VARCHAR2(50 CHAR)		NOT NULL,
	"CLOB"	CLOB		NOT NULL
);

COMMENT ON COLUMN "PSTR"."PSTR_ID" IS 'PT-연월일(8자리)-일련번호(6자리)';

ALTER TABLE "MV" ADD CONSTRAINT "PK_MV" PRIMARY KEY (
	"MV_ID"
);

ALTER TABLE "GNR" ADD CONSTRAINT "PK_GNR" PRIMARY KEY (
	"GNR_ID"
);

ALTER TABLE "MV_GNR" ADD CONSTRAINT "PK_MV_GNR" PRIMARY KEY (
	"MV_GNR_ID"
);

ALTER TABLE "INVLVD" ADD CONSTRAINT "PK_INVLVD" PRIMARY KEY (
	"INVLVD_ID"
);

ALTER TABLE "KWRD" ADD CONSTRAINT "PK_KWRD" PRIMARY KEY (
	"KWRD_ID"
);

ALTER TABLE "BCKGRND" ADD CONSTRAINT "PK_BCKGRND" PRIMARY KEY (
	"BCKGRND_ID"
);

ALTER TABLE "FLMMR" ADD CONSTRAINT "PK_FLMMR" PRIMARY KEY (
	"FLMMKR_ID"
);

ALTER TABLE "VD" ADD CONSTRAINT "PK_VD" PRIMARY KEY (
	"VD_ID"
);

ALTER TABLE "APPR" ADD CONSTRAINT "PK_APPR" PRIMARY KEY (
	"APPR_ID"
);

ALTER TABLE "MV_KWRD" ADD CONSTRAINT "PK_MV_KWRD" PRIMARY KEY (
	"MV_KWRD_ID"
);

ALTER TABLE "PSTR" ADD CONSTRAINT "PK_PSTR" PRIMARY KEY (
	"PSTR_ID"
);

ALTER TABLE "MV_GNR" ADD CONSTRAINT "FK_MV_TO_MV_GNR_1" FOREIGN KEY (
	"MV_ID"
)
REFERENCES "MV" (
	"MV_ID"
);

ALTER TABLE "MV_GNR" ADD CONSTRAINT "FK_GNR_TO_MV_GNR_1" FOREIGN KEY (
	"GNR_ID2"
)
REFERENCES "GNR" (
	"GNR_ID"
);

ALTER TABLE "BCKGRND" ADD CONSTRAINT "FK_MV_TO_BCKGRND_1" FOREIGN KEY (
	"MV_ID"
)
REFERENCES "MV" (
	"MV_ID"
);

ALTER TABLE "FLMMR" ADD CONSTRAINT "FK_MV_TO_FLMMR_1" FOREIGN KEY (
	"MV_ID"
)
REFERENCES "MV" (
	"MV_ID"
);

ALTER TABLE "FLMMR" ADD CONSTRAINT "FK_INVLVD_TO_FLMMR_1" FOREIGN KEY (
	"INVLVD_ID"
)
REFERENCES "INVLVD" (
	"INVLVD_ID"
);

ALTER TABLE "VD" ADD CONSTRAINT "FK_MV_TO_VD_1" FOREIGN KEY (
	"MV_ID"
)
REFERENCES "MV" (
	"MV_ID"
);

ALTER TABLE "APPR" ADD CONSTRAINT "FK_MV_TO_APPR_1" FOREIGN KEY (
	"MV_ID"
)
REFERENCES "MV" (
	"MV_ID"
);

ALTER TABLE "APPR" ADD CONSTRAINT "FK_INVLVD_TO_APPR_1" FOREIGN KEY (
	"INVLVD_ID"
)
REFERENCES "INVLVD" (
	"INVLVD_ID"
);

ALTER TABLE "MV_KWRD" ADD CONSTRAINT "FK_MV_TO_MV_KWRD_1" FOREIGN KEY (
	"MV_ID"
)
REFERENCES "MV" (
	"MV_ID"
);

ALTER TABLE "MV_KWRD" ADD CONSTRAINT "FK_KWRD_TO_MV_KWRD_1" FOREIGN KEY (
	"KWRD_ID2"
)
REFERENCES "KWRD" (
	"KWRD_ID"
);

ALTER TABLE "PSTR" ADD CONSTRAINT "FK_MV_TO_PSTR_1" FOREIGN KEY (
	"MV_ID"
)
REFERENCES "MV" (
	"MV_ID"
);

